import os
env = Environment(ENV = os.environ)

env['F90'] = 'gfortran'
env.Append(FFLAGS='-g',
           F90PATH=['/home/ssobhani/Cantera/cantera/Install_dir/include/cantera'],
           LIBS=['cantera_fortran', 'cantera', 'blas', 'lapack', 'stdc++'],
           LIBPATH=['/home/ssobhani/Cantera/cantera/Install_dir/lib'],
           LINKFLAGS=['-g', '-pthread'],
           FRAMEWORKS=[])

program = env.Program('demo', 'demo.f90')
Default(program)
