import os
env = Environment(ENV = os.environ)

env['F77'] = 'gfortran'
env['CC'] = 'mpicc'
env.Append(FFLAGS='-g',
           CCFLAGS='-g',
           CPPPATH=['/home/ssobhani/Cantera/cantera/Install_dir/include'],
           LIBS=['cantera_fortran', 'cantera', 'blas', 'lapack', 'stdc++'],
           LIBPATH=['/home/ssobhani/Cantera/cantera/Install_dir/lib'],
           LINKFLAGS=['-g', '-pthread'],
           FRAMEWORKS=[])

ctlib = env.Object('demo_ftnlib.cpp')

demo = env.Program('demo', [ctlib, 'demo.f'],
                   LINK='$F77')
isentropic = env.Program('isentropic', [ctlib, 'isentropic.f'],
                         LINK='$F77')

Default(demo)
Default(isentropic)
